### Notebook 5 - (Mariana Grau - Grupo 4)

In [5]:
import numpy as np

In [6]:
#1-Arreglo de ceros de longitud 12
array_ceros = np.zeros(12)
print(array_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
#2-Arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5

array_ceros2 = np.zeros(10)
array_ceros2 [4]=10
print(array_ceros2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [8]:
#3-Arreglo que tenga los números del 10 al 49
array_con_intervalo = np.arange(10,50)
print(array_con_intervalo)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
#4-Arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
array2d = np.array ([[0,1,2],[3,4,5],[6,7,8]])
print(array2d)

print(array2d.ndim)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
2


In [10]:
#5-Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza

array_aleatorio =np.random.rand(100).round(2)

media= np.mean (array_aleatorio).round(2)
varianza= np.var (array_aleatorio).round(2)

print(array_aleatorio)
print("La media es de:", media)
print("La varianza es de:",varianza)

[0.68 0.9  0.37 0.61 0.54 0.11 0.09 0.78 0.71 0.14 0.5  0.59 0.6  0.89
 0.23 0.12 0.37 0.99 0.03 0.03 0.42 0.52 0.89 0.77 0.28 0.69 0.68 0.7
 0.44 0.4  0.72 0.4  0.3  0.26 0.62 0.01 0.8  0.49 0.84 0.7  0.52 0.05
 0.53 0.99 0.39 0.44 0.   0.2  0.05 0.48 0.23 0.71 0.56 0.82 0.28 0.56
 0.11 0.07 0.05 0.84 0.19 0.96 0.18 0.4  1.   0.4  0.13 0.21 0.18 0.35
 0.59 0.21 0.31 0.34 0.6  0.73 0.27 0.13 0.41 0.86 0.51 0.92 0.33 0.3
 0.44 0.83 0.52 0.35 0.11 0.26 0.72 0.   0.38 0.45 0.57 0.67 0.24 0.75
 0.99 0.32]
La media es de: 0.46
La varianza es de: 0.08


In [11]:
#6 Media de un arreglo usando np.sum

array = np.array([25,30,57,56,])
media = ((np.sum (array)) / 4 )

#Otra forma de resolverlo

media2 =np.sum(array)/len(array)


print("La media del arreglo es de",media)
print("La media del arreglo es de",media2)


La media del arreglo es de 42.0
La media del arreglo es de 42.0


In [14]:
#7-Varianza de un arreglo usando np.sum y np.mean

array2 = np.array ([2,4,5,3])
media_array =np.mean(array2)
suma_array =np.sum(array2)

varianza = np.sum((array2 - media_array) ** 2) / len(array2)
varianza2= np.var(array2)

#Otra prueba con los datos de la consigna #6.

varianza3 =np.sum((array - media)**2)/4
varianza4 =np.var(array)


print("La varianza es de",varianza)
print("La varianza es de",varianza2)
print("La varianza es de",varianza3)
print("La varianza es de",varianza4)

La varianza es de 1.25
La varianza es de 1.25
La varianza es de 213.5
La varianza es de 213.5


In [15]:
#8-Array de números aleatorios usando np.random.randn.

array_numeros_aleatorios = np.random.randn (23).round(2)
print(array_numeros_aleatorios)


[ 1.34  2.67  0.05 -1.72 -0.87  0.03 -0.47  0.19  0.18 -0.15  0.46 -0.63
  1.16 -1.45  0.01 -0.89 -1.39  2.    0.26 -0.69 -0.4  -1.18 -1.59]
